// Holds redux action types

export const INSERT_USER_STATE = 'INSERT_USER_STATE';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const SELECT_CONVERSATION = 'SELECT_CONVERSATION';
export const INSERT_CONVERSATION = 'INSERT_CONVERSATION';
export const GET_CONVERSATIONS = 'GET_CONVERSATIONS';